spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/rede_restaurantes}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true


server:
  port: ${PORT:5001}
  error:
    include-message: always
  servlet:
    context-path: /api
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:5000}

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

security:
  jwt:
    secret-key: ${JWT_SECRET:CC6rCcdNxk3yvTM+QEH5ISx52iMKEZB7Qi7ptpjP3ws24cdQhMwthZpKEhNiiF7MpIYxiWkZwnEg3kuWftHoiw==}
    expiration-time: ${JWT_EXPIRATION_MS:3600000}